# -*- coding: utf-8 -*-
"""Exercise1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lygk57yEepB8AYkWjV01mlAyz5uIBR-J
"""

from random import *
print ('Enter Game type:' )
gameType = input()
listCity = ['Lome','Kpalime','Tsevie','Sokode','Vogan','Kara','Dapaong','Bassar','Atakpame','Cinkasse','Keve','Aneho','Bafilo','Notse','Badou']
playoffCity = choice(listCity)
print ('Generating Playoff City 1:', playoffCity)
playoffCity = choice(listCity)
print ('Generating Playoff City 2:', playoffCity)